import { TEST_SLIDER_DATA } from './test';
import { NAVIGATE_LINKS } from './navigate-consts';
import {
  HEADER_TOP_SEARCH_SECTION_TITLE,
  OUR_BEST_BOOK_SECTION_TITLE,
  SHOPPING_SECTION_TITLE_PART_1,
  SHOPPING_SECTION_TITLE_PART_2,
} from './titles-consts';

import {
  HOME_PAGE_SEARCH_SECTION_TEXT,
  SHOPPING_SECTION_TEXT,
  SHOPPING_SECTION_BUTTON,
} from './texts-consts';

export {
  TEST_SLIDER_DATA,
  NAVIGATE_LINKS,
  HEADER_TOP_SEARCH_SECTION_TITLE,
  OUR_BEST_BOOK_SECTION_TITLE,
  HOME_PAGE_SEARCH_SECTION_TEXT,
  SHOPPING_SECTION_TITLE_PART_1,
  SHOPPING_SECTION_TITLE_PART_2,
  SHOPPING_SECTION_TEXT,
  SHOPPING_SECTION_BUTTON,
};
